# the file to store settings and user data in
database: Database.db

# cogs to load, if you dont know what they are just leave them like this
cogs:
        - help
        - settings
        - admin
        - fun
        - info

# these are not admins on your server, but users that can run dangerous commands on the bot.
admins:
        - 366331361583169537  # vivax, the creator of the bot.

invite: https://discord.com/oauth2/authorize?client_id=723933097997107260&permissions=8&scope=bot
source: https://github.com/vivax3794/ABGDB


8ball:
        yes:
                - you can count on it!
                - why not? cant hurt, can it?
                - of course!
                - my predictions say yes.
        no:
                - never
                - of course no!
                - would never work.
                - that will always be a no
        maybe:
                - idk
                - dont ask me
                - I dont care
                - shut up I am sleeping!
                - maybe dont ask a random number generator questions and expect good responses?
