name: test-code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
              pip install pipenv
              pipenv sync
    - name: run flake8
      run: |
              pipenv run lint
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
              pip install pipenv
              pipenv sync
    - name: run mypy
      run: |
              pipenv run mypy --ignore-missing-imports .
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
              pip install pipenv
              pipenv sync
    - name: run pytest
      run: |
              pipenv run test

    - name: upload coverage
      env: # Or as an environment variable
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
              bash <(curl -s https://codecov.io/bash)
